---
# tasks file for http
  
- name: install the apache2 server
  ansible.builtin.apt:
    name: apache2
    state: present
- name: copy the files owner and group permission
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'
